In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data1=pd.read_csv('D:\\Manisha\\FraudTransaction\\Dataset\\bs140513_032310.csv')

In [3]:
data1.head()

step       customer  age gender zipcodeOri       merchant zipMerchant  \
0     0  'C1093826151'  '4'    'M'    '28007'   'M348934600'     '28007'   
1     0   'C352968107'  '2'    'M'    '28007'   'M348934600'     '28007'   
2     0  'C2054744914'  '4'    'F'    '28007'  'M1823072687'     '28007'   
3     0  'C1760612790'  '3'    'M'    '28007'   'M348934600'     '28007'   
4     0   'C757503768'  '5'    'M'    '28007'   'M348934600'     '28007'   

              category  amount  fraud  
0  'es_transportation'    4.55      0  
1  'es_transportation'   39.68      0  
2  'es_transportation'   26.89      0  
3  'es_transportation'   17.25      0  
4  'es_transportation'   35.72      0

In [4]:
data1.shape

(594643, 10)

In [5]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594643 entries, 0 to 594642
Data columns (total 10 columns):
step           594643 non-null int64
customer       594643 non-null object
age            594643 non-null object
gender         594643 non-null object
zipcodeOri     594643 non-null object
merchant       594643 non-null object
zipMerchant    594643 non-null object
category       594643 non-null object
amount         594643 non-null float64
fraud          594643 non-null int64
dtypes: float64(1), int64(2), object(7)
memory usage: 45.4+ MB


In [6]:
data1.describe()

step         amount          fraud
count  594643.000000  594643.000000  594643.000000
mean       94.986827      37.890135       0.012108
std        51.053632     111.402831       0.109369
min         0.000000       0.000000       0.000000
25%        52.000000      13.740000       0.000000
50%        97.000000      26.900000       0.000000
75%       139.000000      42.540000       0.000000
max       179.000000    8329.960000       1.000000

In [7]:
data1.describe(include='object')

customer     age  gender zipcodeOri       merchant zipMerchant  \
count          594643  594643  594643     594643         594643      594643   
unique           4112       8       4          1             50           1   
top     'C1978250683'     '2'     'F'    '28007'  'M1823072687'     '28007'   
freq              265  187310  324565     594643         299693      594643   

                   category  
count                594643  
unique                   15  
top     'es_transportation'  
freq                 505119

In [8]:
#zipcodeOri and zipMerchant doesn't have any predictive power, zero variance(unique value)
data1=data1.drop(columns=['zipcodeOri', 'zipMerchant'])

In [9]:
data1.shape

(594643, 8)

In [10]:
data1.groupby('fraud').size()

fraud
0    587443
1      7200
dtype: int64

In [11]:
data1.groupby('gender').size()

gender
'E'      1178
'F'    324565
'M'    268385
'U'       515
dtype: int64

In [12]:
#Percentage Event rate
data1.groupby('fraud').size()/len(data1)*100

fraud
0    98.789189
1     1.210811
dtype: float64

In [13]:
(data1.groupby('category').size()).sort_values(ascending=False)

category
'es_transportation'        505119
'es_food'                   26254
'es_health'                 16133
'es_wellnessandbeauty'      15086
'es_fashion'                 6454
'es_barsandrestaurants'      6373
'es_hyper'                   6098
'es_sportsandtoys'           4002
'es_tech'                    2370
'es_home'                    1986
'es_hotelservices'           1744
'es_otherservices'            912
'es_contents'                 885
'es_travel'                   728
'es_leisure'                  499
dtype: int64

In [14]:
#(data1.groupby(['category','Fraud']).size()).sort_values(ascending=False)

#tips.groupby('day').agg({'tip':np.mean, 'day':np.size})
data1.groupby(['category','fraud']).size()

category                 fraud
'es_barsandrestaurants'  0          6253
                         1           120
'es_contents'            0           885
'es_fashion'             0          6338
                         1           116
'es_food'                0         26254
'es_health'              0         14437
                         1          1696
'es_home'                0          1684
                         1           302
'es_hotelservices'       0          1196
                         1           548
'es_hyper'               0          5818
                         1           280
'es_leisure'             0            25
                         1           474
'es_otherservices'       0           684
                         1           228
'es_sportsandtoys'       0          2020
                         1          1982
'es_tech'                0          2212
                         1           158
'es_transportation'      0        505119
'es_travel'              0

In [15]:
data2=pd.read_csv('D:\\Manisha\\FraudTransaction\\Dataset\\bsNET140513_032310.csv')

In [16]:
data2.head()

Source         Target  Weight            typeTrans  fraud
0  'C1093826151'   'M348934600'    4.55  'es_transportation'      0
1   'C352968107'   'M348934600'   39.68  'es_transportation'      0
2  'C2054744914'  'M1823072687'   26.89  'es_transportation'      0
3  'C1760612790'   'M348934600'   17.25  'es_transportation'      0
4   'C757503768'   'M348934600'   35.72  'es_transportation'      0

In [17]:
data2.shape

(594643, 5)

# Using Data1 for model building 

In [18]:
data1.head()

step       customer  age gender       merchant             category  \
0     0  'C1093826151'  '4'    'M'   'M348934600'  'es_transportation'   
1     0   'C352968107'  '2'    'M'   'M348934600'  'es_transportation'   
2     0  'C2054744914'  '4'    'F'  'M1823072687'  'es_transportation'   
3     0  'C1760612790'  '3'    'M'   'M348934600'  'es_transportation'   
4     0   'C757503768'  '5'    'M'   'M348934600'  'es_transportation'   

   amount  fraud  
0    4.55      0  
1   39.68      0  
2   26.89      0  
3   17.25      0  
4   35.72      0

In [19]:
data1.groupby('customer').agg({'fraud':'sum','category':'count' }).reset_index().\
rename(columns = {'category':'num_transactions', 'fraud':'num_frauds'})

customer  num_frauds  num_transactions
0     'C1000148617'           1               131
1      'C100045114'           5               109
2     'C1000699316'           0                94
3     'C1001065306'          11                30
4     'C1002658784'           0               131
5     'C1002759277'           0               164
6     'C1004109477'           0               162
7     'C1004300450'           0               179
8     'C1004532392'           0                82
9     'C1005126300'           0               178
10    'C1005495267'           0               177
11    'C1005806982'           1                22
12    'C1006176917'           0               169
13    'C1007572087'           3               150
14    'C1007790716'           0               167
15    'C1008918174'           0                95
16    'C1009080922'           0               170
17     'C100992504'           0               176
18      'C10105795'           0               169
19    'C1010589026'           0               171
20    'C1010865894'           0               172
21    'C1010936270'           1               166
22    'C1011693897'           0               171
23    'C1012876398'           4                20
24    'C1013199152'           1               134
25    'C1013313546'           4               164
26    'C1014010834'           0               178
27    'C1014124305'           0               165
28    'C1014313887'           2               165
29    'C1014347664'           8               174
...             ...         ...               ...
4082   'C986156699'           0               165
4083   'C986553990'           0               166
4084    'C98687952'           0               156
4085    'C98707741'           0               152
4086   'C987620594'           1               165
4087   'C987677028'           2               173
4088   'C987955759'           0               167
4089   'C989137021'           0               166
4090   'C989137613'           4                20
4091   'C989321907'           0               119
4092    'C99017559'           0               177
4093   'C990997956'           1               168
4094   'C991774315'           0               169
4095    'C99215049'           0               172
4096   'C993027768'           4               177
4097   'C993553940'           0               168
4098   'C994449484'           3                33
4099   'C994739890'           0               175
4100   'C995235283'           0                85
4101   'C995746715'           2               106
4102   'C995844287'           7               146
4103    'C99594781'           0               181
4104   'C996326258'           0               125
4105   'C996804095'           1               173
4106   'C997029022'           1                92
4107    'C99729647'           0               175
4108   'C998690782'           2               171
4109   'C998987490'           0               177
4110   'C999393223'           2               142
4111   'C999723254'           1               122

[4112 rows x 3 columns]

In [20]:
df=data1.groupby('customer').agg({'fraud':'sum','category':'count' }).reset_index().\
rename(columns = {'category':'num_transactions', 'fraud':'num_frauds'})

In [21]:
df['ratio_fraud']=df['num_frauds']/df['num_transactions']

In [22]:
df.head()

customer  num_frauds  num_transactions  ratio_fraud
0  'C1000148617'           1               131     0.007634
1   'C100045114'           5               109     0.045872
2  'C1000699316'           0                94     0.000000
3  'C1001065306'          11                30     0.366667
4  'C1002658784'           0               131     0.000000

In [23]:
data1=pd.merge(data1, df[['customer', 'ratio_fraud']], on='customer')

In [24]:
data1.head()

step       customer  age gender      merchant             category  amount  \
0     0  'C1093826151'  '4'    'M'  'M348934600'  'es_transportation'    4.55   
1     1  'C1093826151'  '4'    'M'  'M855959430'           'es_hyper'   14.38   
2     2  'C1093826151'  '4'    'M'  'M348934600'  'es_transportation'   37.21   
3     3  'C1093826151'  '4'    'M'  'M348934600'  'es_transportation'   31.63   
4     4  'C1093826151'  '4'    'M'  'M348934600'  'es_transportation'   35.86   

   fraud  ratio_fraud  
0      0          0.0  
1      0          0.0  
2      0          0.0  
3      0          0.0  
4      0          0.0

In [25]:
data1=data1.drop(columns=['customer'])

In [26]:
data1.head()

step  age gender      merchant             category  amount  fraud  \
0     0  '4'    'M'  'M348934600'  'es_transportation'    4.55      0   
1     1  '4'    'M'  'M855959430'           'es_hyper'   14.38      0   
2     2  '4'    'M'  'M348934600'  'es_transportation'   37.21      0   
3     3  '4'    'M'  'M348934600'  'es_transportation'   31.63      0   
4     4  '4'    'M'  'M348934600'  'es_transportation'   35.86      0   

   ratio_fraud  
0          0.0  
1          0.0  
2          0.0  
3          0.0  
4          0.0

In [27]:
data1['amount'] = np.log(data1['amount']+1)

In [28]:
x=list(data1.columns)

In [29]:
x.remove('fraud')

In [30]:
x

['step', 'age', 'gender', 'merchant', 'category', 'amount', 'ratio_fraud']

In [31]:
X=data1.loc[:,x].values
y=data1.iloc[:, 6].values

In [32]:
X

array([[0, "'4'", "'M'", ..., "'es_transportation'", 1.713797927758343,
        0.0],
       [1, "'4'", "'M'", ..., "'es_hyper'", 2.733067964077498, 0.0],
       [2, "'4'", "'M'", ..., "'es_transportation'", 3.6430972614588084,
        0.0],
       ...,
       [152, "'3'", "'F'", ..., "'es_sportsandtoys'", 4.186011750747925,
        0.8],
       [152, "'3'", "'F'", ..., "'es_home'", 4.9426419229423875, 0.8],
       [152, "'3'", "'F'", ..., "'es_home'", 6.423717631972529, 0.8]],
      dtype=object)

In [33]:
y

array([0, 0, 0, ..., 0, 1, 1], dtype=int64)

In [34]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [35]:
labelencoder_X1=LabelEncoder()
X[:,1]=labelencoder_X1.fit_transform(X[:,1])

labelencoder_X2=LabelEncoder()
X[:,2]=labelencoder_X2.fit_transform(X[:,2])

labelencoder_X3=LabelEncoder()
X[:,3]=labelencoder_X3.fit_transform(X[:,3])

labelencoder_X4=LabelEncoder()
X[:,4]=labelencoder_X4.fit_transform(X[:,4])


In [36]:
X

array([[0, 4, 2, ..., 12, 1.713797927758343, 0.0],
       [1, 4, 2, ..., 7, 2.733067964077498, 0.0],
       [2, 4, 2, ..., 12, 3.6430972614588084, 0.0],
       ...,
       [152, 3, 1, ..., 10, 4.186011750747925, 0.8],
       [152, 3, 1, ..., 5, 4.9426419229423875, 0.8],
       [152, 3, 1, ..., 5, 6.423717631972529, 0.8]], dtype=object)

In [37]:
# Encoding categorical data
onehotencoder = OneHotEncoder(categorical_features=[1,2,3,4])
X = onehotencoder.fit_transform(X).toarray()

C:\Users\gautam\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\gautam\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [38]:
X

array([[  0.        ,   0.        ,   0.        , ...,   0.        ,
          1.71379793,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   1.        ,
          2.73306796,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   2.        ,
          3.64309726,   0.        ],
       ...,
       [  0.        ,   0.        ,   0.        , ..., 152.        ,
          4.18601175,   0.8       ],
       [  0.        ,   0.        ,   0.        , ..., 152.        ,
          4.94264192,   0.8       ],
       [  0.        ,   0.        ,   0.        , ..., 152.        ,
          6.42371763,   0.8       ]])

In [39]:
y

array([0, 0, 0, ..., 0, 1, 1], dtype=int64)

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=0)

In [41]:
X_train

array([[  0.        ,   0.        ,   0.        , ...,  40.        ,
          4.21582446,   0.        ],
       [  0.        ,   0.        ,   1.        , ..., 148.        ,
          3.26614102,   0.        ],
       [  0.        ,   0.        ,   0.        , ..., 154.        ,
          1.33500107,   0.        ],
       ...,
       [  0.        ,   0.        ,   0.        , ...,  23.        ,
          3.26804687,   0.        ],
       [  0.        ,   0.        ,   1.        , ...,  24.        ,
          3.45062226,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,  41.        ,
          4.12277004,   0.        ]])

In [42]:
X_test

array([[  0.        ,   0.        ,   0.        , ...,  54.        ,
          3.34073941,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,  19.        ,
          3.3502549 ,   0.        ],
       [  0.        ,   0.        ,   0.        , ..., 167.        ,
          3.53310245,   0.        ],
       ...,
       [  0.        ,   0.        ,   1.        , ..., 112.        ,
          3.42230634,   0.        ],
       [  0.        ,   0.        ,   1.        , ...,  28.        ,
          4.39358458,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,  53.        ,
          3.65893558,   0.        ]])

In [43]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)



# DecisionTree

In [44]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [45]:
y_pred=classifier.predict(X_test)

In [46]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred)
cm

array([[117207,    282],
       [   284,   1156]], dtype=int64)

In [47]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, y_pred)

0.9001887765379455

# Random Forest

In [48]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=100, criterion='entropy', random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [49]:
y_pred=classifier.predict(X_test)

In [50]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred)
cm

array([[117357,    132],
       [   250,   1190]], dtype=int64)

In [51]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, y_pred)

0.9126326897269815

# SVM(Kernal=Poly)

In [52]:
from sklearn.svm import SVC
classifier=SVC(kernel='poly', random_state=0)
classifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='poly', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False)

In [53]:
y_pred=classifier.predict(X_test)

In [54]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred)
cm

array([[117315,    174],
       [   298,   1142]], dtype=int64)

In [55]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, y_pred)

0.8957872829229404

# XGBoost

In [62]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, learning_rate=0.1,
       max_delta_step=0, max_depth=3, min_child_weight=1, missing=None,
       n_estimators=100, n_jobs=1, nthread=None,
       objective='binary:logistic', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=None,
       subsample=1, verbosity=1)

In [63]:
y_pred=classifier.predict(X_test)

In [64]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred)
cm

array([[117332,    157],
       [   282,   1158]], dtype=int64)

In [65]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, y_pred)

0.901415185676957

In [66]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X=X_train, y=y_train, cv =10)
accuracies.mean()


0.9962981959126364

In [67]:
accuracies

array([0.99630034, 0.99634239, 0.9961532 , 0.99642647, 0.99640537,
       0.99600597, 0.99642639, 0.99625822, 0.99615312, 0.99651048])

# SVM Kernal=Linear

In [68]:
from sklearn.svm import SVC
classifier=SVC(kernel='linear', random_state=0)
classifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False)

In [69]:
y_pred=classifier.predict(X_test)

In [70]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred)
cm

array([[117342,    147],
       [   318,   1122]], dtype=int64)

In [71]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, y_pred)

0.8889577428525225

# Logistic Regression

In [72]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)

C:\Users\gautam\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [73]:
y_pred=classifier.predict(X_test)

In [74]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred)
cm

array([[117324,    165],
       [   322,   1118]], dtype=int64)

In [75]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, y_pred)

0.8874922510476159

In [76]:

xyz=classifier.predict_proba(X_test) 


In [77]:
xyz

array([[9.99986450e-01, 1.35504182e-05],
       [9.99988289e-01, 1.17107061e-05],
       [9.99965583e-01, 3.44166455e-05],
       ...,
       [9.99977756e-01, 2.22436362e-05],
       [9.99960952e-01, 3.90482680e-05],
       [9.99979934e-01, 2.00663790e-05]])

In [78]:
sum(y_test)

1440

In [79]:
y_temp=[]
count=0
i=0
for i in range(len(xyz)):
    if xyz[i][1]>0.3:
        y_temp.append(1)
    else:
        y_temp.append(0)

In [80]:
sum(y_temp)

1554

In [81]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, y_temp)

0.9183234441096613

In [82]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred)
cm

array([[117324,    165],
       [   322,   1118]], dtype=int64)

In [83]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_temp)
cm

array([[117144,    345],
       [   231,   1209]], dtype=int64)

In [84]:
#Precision=ture positive/(false positiive + true positive)
1333/(1333+723)

0.6483463035019456

In [85]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    117489
           1       0.87      0.78      0.82      1440

   micro avg       1.00      1.00      1.00    118929
   macro avg       0.93      0.89      0.91    118929
weighted avg       1.00      1.00      1.00    118929



In [86]:
print(classification_report(y_test, y_temp))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    117489
           1       0.78      0.84      0.81      1440

   micro avg       1.00      1.00      1.00    118929
   macro avg       0.89      0.92      0.90    118929
weighted avg       1.00      1.00      1.00    118929

